# Generated by Django 5.1.3 on 2024-11-21 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('edit_source', models.TextField(blank=True, null=True)),
                ('sentiment_analysis', models.FloatField(blank=True, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='audio_files/')),
            ],
        ),
    ]
